fixtures:
  repositories:
    'stdlib':
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: '4.2.0'
    'concat':
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
      ref: '2.1.0'
  symlinks:
    'sendmail': "#{source_dir}"
