fixtures:
  repositories:
    'stdlib':
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: '4.14.0'
    'concat':
      repo: git://github.com/puppetlabs/puppetlabs-concat.git
      ref: '3.0.0'
  symlinks:
    'sendmail': "#{source_dir}"
