language: ruby
gemfile: .gemfile
script: "rake lint spec"
rvm:
  - 1.9.3
  - 2.0.0
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.7.5
notifications:
  on_success: change
  on_failure: change
